
loremReturn(int length){
  const String lorem =
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum odor amet, consectetuer adipiscing elit. Eleifend rhoncus potenti faucibus; porttitor enim est. In accumsan sapien magnis dapibus eros mollis! Nullam sit nec at; quis ultrices natoque. Orci fusce elit maecenas ullamcorper; suspendisse vulputate dis. Lobortis justo dignissim elementum justo per ante augue quisque.";
  length = (length > lorem.length) ? lorem.length : length;
  return lorem.substring(0, length);
}

//TODO: Improve this function.
// Purus accumsan class praesent bibendum condimentum maecenas, parturient accumsan. Mauris ligula adipiscing scelerisque, suscipit urna eget. Ante nullam convallis semper nullam augue odio. Quam curabitur natoque maximus inceptos augue dis ornare gravida. Ex odio nulla tristique augue nulla aptent. Interdum a rutrum primis aptent porta suspendisse. Lectus et proin class ornare massa. Ad non primis nibh iaculis ullamcorper vel ipsum dapibus. Faucibus lacinia varius scelerisque ullamcorper cursus posuere. Facilisis dolor amet sociosqu elit morbi convallis condimentum.
// Bibendum vestibulum arcu parturient aenean convallis fames sagittis. Porta varius feugiat curae dignissim nulla vestibulum. Tristique consectetur sed dictum platea tincidunt. Aliquam quis nulla torquent urna et non finibus. Felis litora ad porttitor consequat scelerisque venenatis. Metus maximus elit accumsan aliquam purus interdum. Donec egestas nulla dignissim; at rutrum tristique. Tellus dui augue magnis, quis montes ornare finibus tellus. Class urna aliquam tempus quam porta ex eros vulputate.
// Litora vestibulum aliquet finibus consequat montes ut. Nostra potenti neque tempus euismod egestas facilisis inceptos venenatis sed. Luctus blandit curabitur ligula accumsan diam ac. Elementum ipsum consequat quam; suscipit sit aenean libero leo. Purus turpis ac facilisis sed neque purus. Aliquet porttitor feugiat pulvinar odio blandit. Lobortis mauris cursus eget; mattis bibendum faucibus pellentesque ante nisi. Rutrum felis elit maecenas commodo quis hendrerit montes. Vehicula rhoncus adipiscing natoque integer eu amet.
// Semper ad leo magna semper netus. Nisl dui parturient sapien eu litora nostra amet. Tortor sapien erat augue aptent amet quis. Venenatis vehicula justo lacus pulvinar placerat per vulputate! Dignissim montes praesent bibendum ridiculus blandit ac. Semper sociosqu eget dapibus eu; rutrum risus. Laoreet donec amet tempor ullamcorper vitae egestas ornare odio. Semper id sapien dictumst iaculis hendrerit. Aliquam quam eget litora; lacus duis dolor.
